# MkDocs configuration file
site_name: Ansible Workshop
copyright: Copyright &copy; Computacenter 2022
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.ccloud.ninja/tgruetzmacher/ansible-workshop-exercises
      name: Project in Gitlab
    - icon: fontawesome/brands/docker
      link: https://gitlab.ccloud.ninja/tgruetzmacher/ansible-workshop-exercises/-/blob/main/dockerfiles/slim/Dockerfile
      name: Container Definition
extra_css:
  - stylesheets/tables.css
  - stylesheets/extra.css
edit_uri: ""
theme:
  name: material
  # Comment in, if you want to make an announcement
  # custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  logo: assets/ansible-logo-black.png
  language: de
  favicon: assets/ansible-logo-black.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: computacenter
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search:
      lang: de
      separator: '[\s]'
  - awesome-pages
  - autolinks
extra_javascript:
  - extra/refresh-on-toggle-dark-light.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - extra/tablesort.js
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
repo_url: https://github.com/TimGrt/Ansible-Workshop-Exercises
repo_name: timgrt/ansible-workshop-exercises
# Navigation definition
nav:
  - "Workshop Overview":
    - index.md
    - demo-environment/demo-environment.md
    - demo-environment/editor-alternatives.md
  - "Day 1":
    - day1/day1-overview.md
    - day1/ansible-core/ansible-core-intro.md
    - day1/ansible-core/ansible-core-basics.md
    - day1/ansible-core/ansible-core-playbook.md
    - day1/ansible-core/ansible-core-variables.md
    - day1/ansible-core/ansible-core-handlers.md
    - day1/ansible-core/ansible-core-templates.md
    - day1/ansible-core/ansible-core-roles.md
    - day1/ansible-core/ansible-core-supplemental.md
  - "Day 2":
    - day2/day2-overview.md
    - day2/automation-platform/automation-platform-intro.md
    - day2/automation-platform/automation-platform-credentials.md
    - day2/automation-platform/automation-platform-projects.md
    - day2/automation-platform/automation-platform-surveys.md
    - day2/automation-platform/automation-platform-rbac.md
    - day2/automation-platform/automation-platform-workflows.md
    - day2/automation-platform/automation-platform-wrapup.md
    - day2/linux-automation-project/grafana-project.md
  - "Day 3":
    - day3/day3-overview.md
    - day3/ansible-navigator/ansible-navigator.md
    - day3/network-automation-project/apic-project.md
