# MkDocs configuration file
site_name: Ansible Workshop
copyright: Copyright &copy; Computacenter 2023
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.ccloud.ninja/tgruetzmacher/ansible-workshop-exercises
      name: Project in Gitlab
    - icon: fontawesome/brands/docker
      link: https://github.com/TimGrt/Ansible-Workshop-Exercises/blob/main/Dockerfile
      name: Container Definition
extra_css:
  - assets/stylesheets/tables.css
extra_javascript:
  - assets/javascripts/extra/refresh-on-toggle-dark-light.js
  - assets/javascripts/extra/tablesort.min.js
  - assets/javascripts/extra/tablesort.js
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - tables
  - toc:
      title: On this page
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: en
      separator: '[\s]'
  - autolinks
  - git-revision-date-localized:
    # This plugin needs a Git executable and the .git folder
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
      fallback_to_build_date: true
      locale: en
  - print-site:
      add_cover_page: true
      add_print_site_banner: true
      cover_page_template: "docs/assets/pdf/cover-page.tpl"
      enabled: !ENV [ENABLED_PRINT_SITE, True]
      print_page_title: ""
      print_site_banner_template: "docs/assets/pdf/print-banner.tpl"
theme:
  name: material
  custom_dir: docs/assets/overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: octicons/terminal-24
  logo: assets/images/ansible-logo-black.png
  language: en
  favicon: assets/images/ansible-logo-black.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/TimGrt/Ansible-Workshop-Exercises
repo_name: timgrt/ansible-workshop-exercises
# Navigation definition
nav:
  - "Workshop Overview":
    - index.md
    - demo-environment/demo-environment.md
    - demo-environment/editor-alternatives.md
  - "Ansible Basics":
    - ansible-basics-overview.md
    - ansible-core/ansible-core-intro.md
    - ansible-core/ansible-core-basics.md
    - ansible-core/ansible-core-playbook.md
    - ansible-core/ansible-core-variables.md
    - ansible-core/ansible-core-conditionals.md
    - ansible-core/ansible-core-loops.md
    - ansible-core/ansible-core-handlers.md
    - ansible-core/ansible-core-templates.md
    - ansible-core/ansible-core-roles.md
    - ansible-core/ansible-core-supplemental.md
  - "Automation Platform":
    - automation-platform-overview.md
    - automation-platform/automation-platform-intro.md
    - automation-platform/automation-platform-credentials.md
    - automation-platform/automation-platform-projects.md
    - automation-platform/automation-platform-surveys.md
    - automation-platform/automation-platform-rbac.md
    - automation-platform/automation-platform-workflows.md
    - automation-platform/automation-platform-wrapup.md
  - "Projects":
    - projects/projects-overview.md
    - projects/linux-automation/grafana-project.md
    - projects/network-automation/apic-project.md
    - projects/cloud-automation/aws-project.md
    - projects/dcim-ipam-automation/netbox-project.md
  - "Ansible Future":
    - ansible-future-overview.md
    - ansible-navigator/ansible-navigator.md
