---
name: Lint markdown files
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: avto-dev/markdown-lint@v1.5.0
